import Foundation

public enum TextosContaSuspensa {
    public static let titulo = String(localized: "Conta suspensa", bundle: bundleApresentacao)
    public static let subtitulo = String(localized: "Sua conta está temporariamente suspensa.", bundle: bundleApresentacao)
    public static let avisoPrincipal = String(localized: "O acesso aos serviços do Frila está suspenso devido a uma ocorrência em análise.", bundle: bundleApresentacao)
    public static let secaoMotivo = String(localized: "Informações da suspensão", bundle: bundleApresentacao)
    public static let motivoTitulo = String(localized: "Motivo informado", bundle: bundleApresentacao)
    public static let desdeTitulo = String(localized: "Suspensa desde", bundle: bundleApresentacao)
    public static let prazoAnaliseDescricao = String(localized: "A Equipe Frila responde contestações em até 5 dias úteis.", bundle: bundleApresentacao)
    public static let secaoContestacao = String(localized: "Contestação", bundle: bundleApresentacao)
    public static let botaoContestar = String(localized: "Contestar suspensão", bundle: bundleApresentacao)
    public static let promptRelato = String(localized: "Descreva seus argumentos para contestar a suspensão…", bundle: bundleApresentacao)
    public static let labelRelato = String(localized: "Motivos da contestação", bundle: bundleApresentacao)
    public static let dicaRelato = String(localized: "Mínimo de 10 caracteres.", bundle: bundleApresentacao)
    public static let botaoEnviar = String(localized: "Enviar contestação", bundle: bundleApresentacao)
    public static let enviando = String(localized: "Enviando contestação…", bundle: bundleApresentacao)
    public static let cancelar = String(localized: "Cancelar", bundle: bundleApresentacao)
    public static let emAnalise = String(localized: "Em análise", bundle: bundleApresentacao)
    public static let protocoloTitulo = String(localized: "Protocolo de contestação", bundle: bundleApresentacao)
    public static let protocoloNumero = String(localized: "Número do protocolo", bundle: bundleApresentacao)
    public static let protocoloData = String(localized: "Enviado em", bundle: bundleApresentacao)
    public static let prazoRespostaTitulo = String(localized: "Previsão de resposta até", bundle: bundleApresentacao)
    public static let mensagemEmAnalise = String(localized: "Sua contestação foi enviada e está em análise pela Equipe Frila. Você receberá uma notificação e resposta por e-mail dentro do prazo informado.", bundle: bundleApresentacao)
    public static let contestacaoJaExiste = String(localized: "Já existe uma contestação para esta suspensão.", bundle: bundleApresentacao)
    public static let relatoMinimo = String(localized: "O relato deve conter pelo menos 10 caracteres.", bundle: bundleApresentacao)
    public static let relatoObrigatorio = String(localized: "Informe o motivo da contestação antes de enviar.", bundle: bundleApresentacao)
    public static let contaReativada = String(localized: "Sua conta foi reativada.", bundle: bundleApresentacao)
    public static let secaoAcoes = String(localized: "Outras ações", bundle: bundleApresentacao)
    public static let exportar = String(localized: "Exportar meus dados", bundle: bundleApresentacao)
    public static let excluir = String(localized: "Excluir conta", bundle: bundleApresentacao)
    public static let sair = String(localized: "Sair da conta", bundle: bundleApresentacao)
    public static let erroSemRede = String(localized: "Sem conexão. Verifique sua internet e tente novamente.", bundle: bundleApresentacao)
    public static let erroGenerico = String(localized: "Não foi possível concluir esta ação. Tente novamente.", bundle: bundleApresentacao)
}
